# Generated by Django 4.2 on 2023-05-18 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arty', '0003_service_remove_membre_groupe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Servicee',
        ),
    ]
