# Generated by Django 4.2 on 2023-05-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arty', '0005_ser_delete_servicee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ser',
        ),
    ]
